---
title: "midterm_021710158_정혜인"
author: "정혜인(2021710158)"
date: "2022-10-18"
output: html_document
---

<style type="text/css">

body{
   font-size: 16px;
}
td {
   font-size: 16px;
}
code.r{
  font-size: 16px;
}
pre {
  font-size: 16px
} 
h1.title {
  font-size: 36px;
}
h1 { /* Header 1 */
  font-size: 28px;
}
h2 { /* Header 2 */
    font-size: 22px;
}

</style>

```{r global_options, R.options=knitr::opts_chunk$set(warning=FALSE, message=FALSE)}
``` 

```{r eval=F}
install.packages(c("data.table", "magrittr", "ggpubr", "rvg", "officer")) 

## setting: permanent storage
credentials::credential_helper_set("store")                   # Linux

## create a personal access token for authentication:
usethis::create_github_token() 
## in case usethis version < 2.0.0: usethis::browse_github_token() (or even better: update usethis!)

## copy and paste your token and press enter
credentials::set_github_pat()
````

```{r}
library(data.table);library(magrittr);library(ggpubr);library(rvg);library(officer) 
aa <- fread("https://raw.githubusercontent.com/jinseob2kim/R-skku-biohrs/main/data/example_g1e.csv")
head(aa)
```

# R을 활용한 보건의료 자료분석론 

## 1. “Q_” 로 시작하는 변수는 범주형(factor)으로, 나머지 변수는 숫자형(integer)으로 만드세요.

```{r}
### Data handling - Set class

# Classify variables
category <- grep("Q_", names(aa), value = T)
continuous <- names(aa)[!names(aa) %in% category]

for (b in category){
  aa[[b]] <-as.factor(aa[[b]])
}
for (b in continuous){
  aa[[b]] <-as.numeric(aa[[b]])
}

summary(aa)
```

## 2. 연속 변수 “WSTC”와 “BMI”의 연도별 평균 및 표준편차를 구하세요.

```{r}
### Data handling - Group by 
meansd <-aggregate(aa[,c("WSTC", "BMI")], by = list(aa$EXMD_BZ_YYYY), function(x){c(mean = mean(x), sd = sd(x))})
meansd
```

## 3. 연도별 “FBS”를 나타내는 Boxplot을 그린 후 pptx로 저장하세요. (x축: “EXMD_BZ_YYYY”, y축: “FBS”)

You can also embed plots, for example:

```{r}
cc <- ggplot(data=aa,aes(x=factor(EXMD_BZ_YYYY),y=FBS))+
  geom_boxplot()+
  ggtitle("FBS by year")+ylab("FBS")+xlab("Year")+
  scale_x_discrete(labels=c("2009","2010","2011","2012","2013","2014","2015"))
cc

plot_file <- read_pptx() %>%
  add_slide() %>% ph_with(dml(ggobj = cc), location=ph_location_type(type="body")) %>%
print(plot_file, target = "midterm_2021710158_정혜인.pptx")

```

